export const MongoSchemaNames = {
  SHIP_EMPLOYEE: 'SHIP_EMPLOYEE',
  SHIP_DEPARTMENT: 'SHIP_DEPARTMENT',
  SHIP_STATEMENT: 'SHIP_STATEMENT',
  SHIP_DONATION: 'SHIP_DONATION',
  SHIP_RATE: 'SHIP_RATE',
} as const;
